### ISSUE TITLE
2014 General Precinct Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ne#15]
UPDATE: @sdunbarne is working on the entire state for this election.

If you want to work on a county, add a comment saying which one you'd like to work on or email openelections@gmail.com. You can either email us finished CSV files or submit a pull request, whatever is easiest. 

The results files you'll be converting are in the [Nebraska sources repository](https://github.com/openelections/openelections-sources-ne/tree/master/2014). Many of these are either PDFs or Excel files, and in some cases you might need to convert a number of office-specific files. For electronic PDFs, we recommend using [Tabula](http://tabula.technology/), which is free, to extract data. The goal is to create a single CSV file for each county, with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For the following offices: U.S. Senate, U.S. House, Governor, Secretary of State, State Treasurer, Attorney General, Auditor and State Legislature (`party` will be blank for State Legislature). File names should be: `20141104__ne__general__{county_name}__precinct.csv`, with the county name lower case and spaces replaced with underscores.

Nebraska does have an [electronic results reporting system](http://electionresults.sos.ne.gov/), but those results are considered unofficial. We'd still take a parser for those, since they are Excel files, though.

- [ ] Adams 
- [ ] Antelope 
- [ ] Arthur 
- [ ] Banner 
- [ ] Blaine 
- [ ] Boone 
- [ ] Box Butte 
- [ ] Boyd 
- [ ] Brown 
- [ ] Buffalo 
- [ ] Burt 
- [ ] Butler 
- [ ] Cass 
- [ ] Cedar 
- [ ] Chase 
- [ ] Cherry 
- [ ] Cheyenne 
- [ ] Clay 
- [ ] Colfax 
- [ ] Cuming 
- [ ] Custer 
- [ ] Dakota 
- [ ] Dawes 
- [ ] Dawson 
- [ ] Deuel 
- [ ] Dixon 
- [ ] Dodge 
- [ ] Douglas 
- [ ] Dundy 
- [ ] Fillmore 
- [ ] Franklin 
- [ ] Frontier 
- [ ] Furnas 
- [ ] Gage 
- [ ] Garden 
- [ ] Garfield 
- [ ] Gosper 
- [ ] Grant 
- [ ] Greeley 
- [ ] Hall 
- [ ] Hamilton 
- [ ] Harlan 
- [ ] Hayes 
- [ ] Hitchcock 
- [ ] Holt 
- [ ] Hooker 
- [ ] Howard 
- [ ] Jefferson 
- [ ] Johnson 
- [ ] Kearney 
- [ ] Keith 
- [ ] Keya Paha 
- [ ] Kimball 
- [ ] Knox 
- [ ] Lancaster 
- [ ] Lincoln 
- [ ] Logan 
- [ ] Loup 
- [ ] Madison 
- [ ] McPherson 
- [ ] Merrick 
- [ ] Morrill 
- [ ] Nance 
- [ ] Nemaha 
- [ ] Nuckolls 
- [ ] Otoe 
- [ ] Pawnee 
- [ ] Perkins 
- [ ] Phelps 
- [ ] Pierce 
- [ ] Platte 
- [ ] Polk 
- [ ] Red Willow 
- [ ] Richardson 
- [ ] Rock 
- [ ] Saline 
- [x] Sarpy 
- [ ] Saunders 
- [ ] Scotts Bluff 
- [ ] Seward 
- [ ] Sheridan 
- [ ] Sherman 
- [ ] Sioux 
- [ ] Stanton 
- [ ] Thayer 
- [ ] Thomas 
- [ ] Thurston 
- [ ] Valley 
- [ ] Washington 
- [ ] Wayne 
- [ ] Webster 
- [ ] Wheeler 
- [ ] York

**Comment by sdunbarne** [comment]
I am just about done converting the excel files for  all 93 counties for the 2014 Nebraska General election to csv format.
I have an excel parser and converter written in R.  I was checking in here to make sure I had the data format correct when I saw this issue.

Remaining things to be done over the next day is to convert all the csv files to the format 
20141104__ne__general__{county_name}__precinct.csv, with the county name lower case and spaces replaced with underscores.  

I don't have the State Legislature offices, but I do have the other 7 offices.  The State Legislature race reporting by precinct is going to take more careful parsing.  The results are reported inconveniently within large counties like Douglas and Lancaster and not consistently across small counties (Adams and Banner counties report no Legislative races, York county has one.)  I will have to sort out why,
and extend the parser to cover these inconveniences and inconsistencies.

**Comment by dwillis** [comment]
Thanks, @sdunbarne! If it's easier for you, you can generate a single statewide file, `20141104__ne__general__precinct.csv`.

**Comment by dwillis** [comment]
@sdunbarne thanks again for your work - what's your judgment on the state legislative races? Are they doable?

**Comment by sdunbarne** [comment]
> the state legislative races? Are they doable?

Yes!, in fact, they're already done!  Check for instance in Sarpy County to
see the 3 legislative races there.
(Figuring out how to do it cleanly took me the extra couple of weeks).

Once again, if the 2012 data is pretty similar, should be able to polish
that off next week, including legislative races.

-- Steve Dunbar

**Comment by dwillis** [comment]
Awesome, thanks!
