### ISSUE TITLE
Parse 2016 general election precinct-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ne#3]
If you want to work on a county, add a comment saying which one you'd like to work on or email openelections@gmail.com. You can either email us finished CSV files or submit a pull request, whatever is easiest. 

The results files you'll be converting are in the [Nebraska sources repository](https://github.com/openelections/openelections-sources-ne/tree/master/2016). Many of these are either PDFs or Excel files, and in some cases you'll need to convert a number of office-specific files. For electronic PDFs, we recommend using [Tabula](http://tabula.technology/), which is free, to extract data. The goal is to create a single CSV file for each county, with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For the following offices: President, U.S. House, and State Legislature (`party` will be blank for State Legislature). File names should be: `20161108__ne__general__{county_name}__precinct.csv`, with the county name lower case and spaces replaced with underscores.

Nebraska does have an [electronic results reporting system](http://electionresults.sos.ne.gov/), but those results are considered unofficial. We'd still take a parser for those, since they are Excel files, though.

- [x] Adams 
- [x] Antelope 
- [x] Arthur 
- [x] Banner 
- [x] Blaine 
- [x] Boone 
- [x] Box Butte 
- [x] Boyd 
- [x] Brown 
- [x] Buffalo 
- [x] Burt 
- [x] Butler 
- [x] Cass 
- [x] Cedar 
- [x] Chase 
- [x] Cherry 
- [x] Cheyenne 
- [x] Clay 
- [x] Colfax 
- [x] Cuming 
- [x] Custer 
- [x] Dakota 
- [x] Dawes 
- [x] Dawson 
- [x] Deuel 
- [x] Dixon 
- [x] Dodge 
- [x] Douglas 
- [x] Dundy 
- [x] Fillmore 
- [x] Franklin 
- [x] Frontier 
- [x] Furnas 
- [x] Gage 
- [x] Garden 
- [x] Garfield 
- [x] Gosper 
- [x] Grant 
- [x] Greeley 
- [x] Hall 
- [x] Hamilton 
- [x] Harlan 
- [x] Hayes 
- [x] Hitchcock 
- [x] Holt 
- [x] Hooker 
- [x] Howard 
- [x] Jefferson 
- [x] Johnson 
- [x] Kearney 
- [x] Keith 
- [x] Keya Paha 
- [x] Kimball 
- [x] Knox 
- [x] Lancaster 
- [x] Lincoln 
- [x] Logan 
- [x] Loup 
- [x] Madison 
- [x] McPherson 
- [x] Merrick 
- [x] Morrill 
- [x] Nance 
- [x] Nemaha 
- [x] Nuckolls 
- [x] Otoe 
- [x] Pawnee 
- [x] Perkins 
- [x] Phelps 
- [x] Pierce 
- [x] Platte 
- [x] Polk 
- [x] Red Willow 
- [x] Richardson 
- [x] Rock 
- [x] Saline 
- [x] Sarpy 
- [x] Saunders 
- [x] Scotts Bluff 
- [x] Seward 
- [x] Sheridan 
- [x] Sherman 
- [x] Sioux 
- [x] Stanton 
- [x] Thayer 
- [x] Thomas 
- [x] Thurston 
- [x] Valley 
- [x] Washington 
- [x] Wayne 
- [x] Webster 
- [x] Wheeler 
- [x] York

**Comment by lephead** [comment]
Would like if you contact a county to please ask for write-ins for President by precinct and absentees by precinct.  Need those, but you won't get every county.

**Comment by cjwinchester** [comment]
@dwillis So to clarify (lol), we want to convert the results files in the repo you linked to, not e.g. parse them out of the [county results file](http://results.enr.clarityelections.com/NE/Sarpy/64652/184054/en/summary.html). Yes? Or does it matter?

**Comment by dwillis** [comment]
@cjwinchester Heh - if the county results file is official, you're free to use that instead of the one in the sources repo. But check to make sure.

**Comment by cjwinchester** [comment]
word, i think we're in business

<img width="199" alt="screen shot 2017-07-31 at 8 03 13 pm" src="https://user-images.githubusercontent.com/3728252/28806108-571bcc4a-762b-11e7-8e25-64ad812f6f34.png">

For now I can take:

- [ ] Sarpy
- [ ] Hall
- [ ] Cheyenne

**Comment by cjwinchester** [comment]
I'll grab:

- [ ] Saunders
- [ ] Thomas
- [ ] Thurston

**Comment by jusjaesho** [comment]
I'll take Boone.
